graph LR
    main.go --> config
    main.go --> logger
    main.go --> db
    main.go --> handler
    main.go --> customMiddleware
    main.go --> enums
    main.go --> payload

    handler --> config
    handler --> logger
    handler --> db
    handler --> enums
    handler --> payload

    customMiddleware --> config
    customMiddleware --> logger
    customMiddleware --> db
    customMiddleware --> enums
    customMiddleware --> payload
